trigger:
- main

pool:
  name: default

steps:
  - script: python --version
    displayName: Check Python installation

  - script: pip install -r requirements.txt
    displayName: Install dependencies

  - script: pytest
    displayName: Run tests